---
- name: Install and configure zsh

  hosts: all

  # Zsh plugins and themes at
  # https://github.com/unixorn/awesome-zsh-plugins
  # https://github.com/zsh-users/antigen
  # https://ohmyz.sh/

  vars:
    users:
      - username: "{{ ansible_user_id }}"
        antigen_libraries:
          - name: oh-my-zsh
        antigen_theme:
          name: denysdovhan/spaceship-prompt
        antigen_bundles:
          # Bundles from the default repo (robbyrussell's oh-my-zsh).
          # - name: autojump
          - name: common-aliases
          - name: command-not-found
          # - name: docker
          - name: extract
          - name: git
          - name: git-extras
          - name: git-flow
          - name: github
          - name: gitignore
          - name: pip
          - name: python
          - name: ssh-agent
          - name: vagrant
          - name: vscode
          - name: web-search
          - name: zsh-autosuggestions
          # Syntax highlighting bundle.
          - name: zsh-syntax-highlighting # `name` is required (any valid file name will do so long as it's unique for the bundles)
            url: zsh-users/zsh-syntax-highlighting

  pre_tasks:
    - name: Update apt-get repo and cache
      become: yes
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
      when: ansible_pkg_mgr == 'apt'

  tasks:
    - name: Install Powerline-fonts
      become: yes
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - fonts-powerline
        - fonts-firacode
      when: ansible_pkg_mgr == 'apt'

    - name: Install Antigen
      import_role:
        name: gantsign.antigen
