---
- name: Configure base services

  hosts: all

  vars:
    ansible_python_interpreter: python3

    # pip_package: "\
    #   {# pip package is python3-pip on *nix and python3 on Darwin #}\
    #   {% if (ansible_os_family | lower ) != 'darwin' %}\
    #     python3-pip\
    #   {% else %}\
    #     python3\
    #   {% endif %}"
    # pip_executable: pip

    packages: [{ name: "python3-apt" }, { name: "python3-pip" }]

  tasks:
    - name: Install Dependencies
      import_role:
        name: greenthegarden.configure_host
