---
- name: Configure base services

  hosts: all

  become: yes

  vars:
    ansible_python_interpreter: python3

    # pip_package: "\
    #   {# pip package is python3-pip on *nix and python3 on Darwin #}\
    #   {% if (ansible_os_family | lower ) != 'darwin' %}\
    #     python3-pip\
    #   {% else %}\
    #     python3\
    #   {% endif %}"
    # pip_executable: pip

    security_fail2ban_enabled: false

    packages: [{ name: "python3-apt" }]

  pre_tasks:
    - name: Install dependencies
      import_role:
        name: greenthegarden.configure_host
        tasks_from: install-packages.yml

  tasks:
    - name: Install and configure security software
      import_role:
        name: geerlingguy.repo-epel
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

    - name: Install and configure security software
      import_role:
        name: geerlingguy.security

    - name: Conigue iptable firewall
      import_role:
        name: geerlingguy.firewall

    - name: Install Dependencies
      import_role:
        name: greenthegarden.configure_host
