---
# Sources:
# https://medium.com/georgian-impact-blog/python-tooling-makes-a-project-tick-181d567eea44
# https://medium.com/@cjolowicz/hypermodern-python-d44485d9d769
# https://medium.com/@vanflymen/blazing-fast-ci-with-github-actions-poetry-black-and-pytest-9e74299dd4a5

# https://medium.com/python-in-plain-english/unit-testing-in-python-tox-and-nox-833e4bbce729

- name: Dependencies

  hosts: all

  vars:
    packages: [{ name: "python3-apt" }]

    python_modules: [{ name: "pip" }]

  tasks:
    - name: Install Dependencies
      import_role:
        name: greenthegarden.configure_host

- name: Install pyenv

  hosts: all

  vars:
    # Update .bashrc and .zshrc shell scripts
    pyenv_init_shell: true

    # Latest Python versions
    pyenv_python38_version: "3.8.1"

    # Python versions to install
    pyenv_python_versions:
      - "{{ pyenv_python38_version }}"

    # Set global pyenv version
    pyenv_global: "{{ pyenv_python38_version }} system"

    # Optionally, install virtualenvwrapper plugin for pyenv
    pyenv_virtualenvwrapper: false
    pyenv_virtualenvwrapper_home: "{{ ansible_env.HOME }}/.virtualenvs"

    # Detect existing install
    pyenv_detect_existing_install: true

  tasks:
    - name: Install pyenv
      import_role:
        name: markosamuli.pyenv

    - name: Download get-poetry.py
      get_url:
        url: https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
        dest: /tmp/get-poetry.py
        mode: "0440"

    - name: Install poetry
      command: /usr/bin/python3 /tmp/get-poetry.py
