---
roles:
  - name: gantsign.antigen
    scm: git
    src: git+https://github.com/gantsign/ansible_role_antigen.git
    version: origin/master

  - name: gantsign.visual-studio-code
    scm: git
    src: git+https://github.com/gantsign/ansible-role-visual-studio-code.git
    version: origin/master

  - name: geerlingguy.docker
    scm: git
    src: git+https://github.com/geerlingguy/ansible-role-docker.git
    version: origin/master

  - name: geerlingguy.firewall
    scm: git
    src: git+https://github.com/geerlingguy/ansible-role-firewall.git
    version: origin/master

  - name: geerlingguy.pip
    scm: git
    src: git+https://github.com/geerlingguy/ansible-role-pip.git
    version: origin/master

  - name: geerlingguy.repo-epel
    scm: git
    src: git+https://github.com/geerlingguy/ansible-role-repo-epel.git
    version: origin/master

  - name: geerlingguy.security
    scm: git
    src: git+https://github.com/geerlingguy/ansible-role-security.git
    version: origin/master

  - name: greenthegarden.configure_host
    scm: git
    src: git+https://github.com/greenthegarden/ansible-role-configure-host.git
    version: origin/master

  - name: oefenweb.virtualbox
    scm: git
    src: git+https://github.com/Oefenweb/ansible-virtualbox.git
    version: origin/master

  - name: markosamuli.pyenv
    scm: git
    src: git+https://github.com/markosamuli/ansible-pyenv.git
    version: origin/master
# collections:
