---

- hosts: all

  vars:
    # override gantsign.visual-studio-code default vars
    visual_studio_code_version: ''
    visual_studio_code_build: stable
    users:
      - username: "{{ ansible_user_id }}"
        visual_studio_code_extensions:
          - vscoss.vscode-ansible # Ansible
          - ms-vscode.azurecli # Azure CLI Tools
          - ms-vsts.team # Azure Repos
          - ms-azuretools.vscode-docker
          - donjayamanne.githistory # Git History
          - felipecaputo.git-project-manager # Git Project Manager
          - eamodio.gitlens # GitLens
          - keesschollaart.vscode-home-assistant # Home Assistant Config Helper
          - yzhang.markdown-all-in-one # Markdown All in One
          - shd101wyy.markdown-preview-enhanced # Markdown Preview Enhanced
          - davidanson.vscode-markdownlint # markdownlint
          - openhab.openhab # openHAB
          - ms-python.python # Python
          - ms-vscode-remote.vscode-remote-extensionpack # Remote Development
          - mauve.terraform # Terraform
          - bbenoist.vagrant # Vagrant
          - visualstudioexptteam.vscodeintellicode # Visual Studio IntelliCode
          - redhat.vscode-yaml # YAML
        visual_studio_code_settings: {
          "editor.fontSize": 11,
          "editor.tabSize": 2
        }

  tasks:
  
    - name: Install Visual Studio Code
      import_role:
        name: gantsign.visual-studio-code
