---

- hosts: all

  vars:
    # override gantsign.visual-studio-code default vars
    visual_studio_code_version: ''
    visual_studio_code_build: stable
    users:
      - username: "{{ ansible_user_id }}"
        visual_studio_code_extensions:
          - vscoss.vscode-ansible # Ansible
          - ms-vscode.atom-keybindings # Atom Keymap
          - ms-vscode.azurecli # Azure CLI Tools
          - vsciot-vscode.azure-iot-tools # Azure IoT Tools
          - ms-vsts.team # Azure Repos
          - alefragnani.bookmarks # Bookmarks
          - coenraads.bracket-pair-colorizer-2 # Bracket pair colorizer 2
          - wmaurer.change-case # Change Case
          - streetsidesoftware.code-spell-checker # Code Spell Checker
          # - IBM.codewind # Codewind
          # - IBM.codewind-openapi-tools # Codewind OpenAPI Tools
          - NgekNgok.vscode-custom-snippets # Custom Snippets
          - ms-azuretools.vscode-docker # Docker
          - henriiik.docker-linter # Docker Linter
          - DmitryDorofeev.empty-indent # Empty Indent
          - donjayamanne.githistory # Git History
          - felipecaputo.git-project-manager # Git Project Manager
          - github.vscode-pull-request-github # GitHub Pull Requests and Issues
          - codezombiech.gitignore # gitignore
          - piotrpalarz.vscode-gitignore-generator # Gitignore Generator
          - eamodio.gitlens # GitLens
          - kameshkotwani.google-search # Google Search
          - wholroyd.hcl # Hashicorp HCL
          - hashicorp.terraform # HashiCorp Terraform
          - zainchen.json #json
          - tberman.json-schema-validator # JSON schema validator
          - eriklynd.json-tools # JSON tools
          - tuxtina.json2yaml # json2yaml
          - ms-vsliveshare.vsliveshare-pack # Live Share Extension Pack
          - yzhang.markdown-all-in-one # Markdown All in One
          - shd101wyy.markdown-preview-enhanced # Markdown Preview Enhanced
          - davidanson.vscode-markdownlint # markdownlint
          - 42Crunch.vscode-openapi # OpenAPI (Swagger) Editor
          - johnpapa.vscode-peacock # Peacock
          - ms-python.python # Python
          - ms-vscode-remote.vscode-remote-extensionpack # Remote Development
          - humao.rest-client # REST Client
          - lextudio.restructuredtext # reStructuredText
          - sonarsource.sonarlint-vscode # SonarLint
          - mauve.terraform # Terraform
          - gruntfuggly.todo-tree # Todo tree
          - bbenoist.vagrant # Vagrant
          - visualstudioexptteam.vscodeintellicode # Visual Studio IntelliCode
          - vscode-icons-team.vscode-icons # VSCode-icons
          - redhat.vscode-yaml # YAML
          # - ricardo-emerson.base-development-extensions-pack

        visual_studio_code_settings: {
          "editor.fontSize": 12,
          "editor.tabSize": 2,
          "editor.insertSpaces": true,
          "editor.detectIndentation": false,
          "cSpell.language": "en-GB",
        }

  tasks:

    - name: Install Visual Studio Code
      import_role:
        name: gantsign.visual-studio-code
